/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BtnDropdown: typeof import('./src/components/BtnDropdown.vue')['default']
    BtnReadCsv: typeof import('./src/components/BtnReadCsv.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    PageHeader: typeof import('./src/components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
